"resources"
{
"de_thematrix_11.nav" "file"
"de_thematrix_11.txt" "file"
"sound/matrix/catmeow.wav" "file"
"sound/matrix/matrixteleport.mp3" "file"
"materials/custommaterials/matrixcode.vmt" "file"
"materials/custommaterials/matrixcode.vtf" "file"
"materials/custommaterials/teleportcode.vmt" "file"
"materials/custommaterials/teleportcode.vtf" "file"
"materials/custommaterials/detector_lights.vtf" "file"
"materials/custommaterials/elebutton_off.vtf" "file"
"materials/custommaterials/elebutton_on.vtf" "file"
"materials/custommaterials/lobbytiles.vtf" "file"
"materials/custommaterials/elevatorpanel.vtf" "file"
"materials/custommaterials/detector_lights.vmt" "file"
"materials/custommaterials/elebutton_off.vmt" "file"
"materials/custommaterials/elebutton_on.vmt" "file"
"materials/custommaterials/lobbytiles.vmt" "file"
"materials/custommaterials/elevatorpanel.vmt" "file"
"materials/custommaterials/backdoor_floor.vtf" "file"
"materials/custommaterials/backdoor_floor.vmt" "file"
}